### ISSUE TITLE
Candidates still ultimately empty 

### ISSUE THREAD

**Issue by bhavna-gopal** [Multi-Objective-NAS/self-supervised-nas#28]
Can you please give us a step by step procedure?

1.  When we run CUDA_VISIBLE_DEVICES={device_index} python3 pretrain.py experiment=AngularLoss we generate some weights in the output folder. We don't see anything with "encoder" in it. We see "embedder", "trunk" and "trunk-optimizer". There are six h5 files in total - each of the above names with "0" and "1" .

2. Passing in the path for embedder does not work into train.yaml. What should we be passing in here?

3. How do we run train.py? I am currently running "CUDA_VISIBLE_DEVICES=4 python3 train.py" sometimes I still see that candidates is empty and sometimes it is not. Is this expected? How do I generate the networks generated/ search space as well as the final network selected?

**Comment by juice500ml** [comment]
Duplicate issue in #28.
